### ISSUE TITLE
Question: Why Not Attach Cover to Camera?

### ISSUE THREAD

**Issue by suicidepills** [aaccurso/phaser-state-transition-plugin#10]
This question is in regards to commit: 881d1e8792663ddccdb981baebeef4207d926a9c

Is there a reason that it's better to attach the transition cover to the game world instead of the camera?  Doesn't this cause issues in cases where the camera position changes from 0,0?

**Comment by aaccurso** [comment]
You are right, if the next state moves the camera away from the world center on the _init_ or _create_ methods (for whatever reason), then **the cover generated in the previous state won't be seen**.
It just happens that on my games I don't usually start the camera other than the world center, so it's a great catch from you!
I'm not making Phaser games anymore so if you like you can fork the repo and do a pull request with this feature. I'll gladly merge it :D
Thanks for the help!

**Comment by suicidepills** [comment]
And done!  Thank you for your reply and willingness to help.  This is
actually the first PR I've ever submitted so let me know if it didn't come
through properly.

Thanks again!

**Comment by aaccurso** [comment]
Merged in #11! Great work, I'm glad you contributed.
Thanks to you!
