### ISSUE TITLE
Blank screen before transition

### ISSUE THREAD

**Issue by yougotashovel** [aaccurso/phaser-state-transition-plugin#7]
Whenever i call a transition, it works.  But it does the following:

1. The screen goes blank for 500ms-2s
2. Then what i assume is the sprite of the current state re-appears
3. Then the transition takes effect.

I have different states preloading different assets, and i think the delay in point 1. might be the time it takes to load these assets.

Any idea why this is happening, or how to fix it? Thanks

**Comment by aaccurso** [comment]
@yougotashovel can you try now?

**Comment by yougotashovel** [comment]
Great! It's working now.
