### ISSUE TITLE
Not working in Canvas+

### ISSUE THREAD

**Issue by yougotashovel** [aaccurso/phaser-state-transition-plugin#9]
When trying to use a transition in Canvas+ the screen just goes blank, and the following error message is given:

**JavaScript Exception ( Tag: 'requestAnimationFrame'): texImage2D Invalid Image or Canvas or ImageData in texImage2D**

--

For some context, Canvas+ displays the following message before looking at the Errors tab:

*If you are experiencing warnings/errors or a black screen during Canvas+ execution, remember that this technology is only able to render HTML5 Canvas elements. Please contact Ludei to fully understand the advantages and limitations of Canvas+*

Not sure if this is beyond the scope of this plugin, but i thought to highlight the issue anyway.

**Comment by aaccurso** [comment]
Hi, I'm not wrapping my apps with Cocoon so I haven't tested the plugin on this platform.
My first guess would be that the plugin is using a feature not supported by Cocoon.
I'll close this issue since it's platform specific, but you can submit a PR with a fix if you like!
